version: "3.9"
services:
  processor:
    build: .
    volumes: [".:/app"]
    command: python main.py
  dashboard:
    build: .
    ports: ["8501:8501"]
    volumes: [".:/app"]
    command: streamlit run src/app/dashboard_streamlit.py --server.address=0.0.0.0
